START TRANSACTION;

ALTER TABLE role_claims DROP CONSTRAINT "FK_role_claims_roles_role_id";

ALTER TABLE user_claims DROP CONSTRAINT "FK_user_claims_users_user_id";

ALTER TABLE user_logins DROP CONSTRAINT "FK_user_logins_users_user_id";

ALTER TABLE user_roles DROP CONSTRAINT "FK_user_roles_roles_role_id";

ALTER TABLE user_roles DROP CONSTRAINT "FK_user_roles_users_user_id";

ALTER TABLE user_tokens DROP CONSTRAINT "FK_user_tokens_users_user_id";

DROP INDEX "EmailIndex";

DROP INDEX "UserNameIndex";

DROP INDEX "IX_user_roles_role_id";

DROP INDEX "IX_user_claims_user_id";

DROP INDEX "RoleNameIndex";

DROP INDEX "IX_role_claims_role_id";

ALTER TABLE services DROP COLUMN city;

CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE users ALTER COLUMN normalized_email TYPE text;

ALTER TABLE users ALTER COLUMN email TYPE text;

UPDATE user_tokens SET name = '' WHERE name IS NULL;
ALTER TABLE user_tokens ALTER COLUMN name SET NOT NULL;
ALTER TABLE user_tokens ALTER COLUMN name SET DEFAULT '';

UPDATE user_tokens SET login_provider = '' WHERE login_provider IS NULL;
ALTER TABLE user_tokens ALTER COLUMN login_provider SET NOT NULL;
ALTER TABLE user_tokens ALTER COLUMN login_provider SET DEFAULT '';

UPDATE user_logins SET provider_key = '' WHERE provider_key IS NULL;
ALTER TABLE user_logins ALTER COLUMN provider_key SET NOT NULL;
ALTER TABLE user_logins ALTER COLUMN provider_key SET DEFAULT '';

UPDATE user_logins SET login_provider = '' WHERE login_provider IS NULL;
ALTER TABLE user_logins ALTER COLUMN login_provider SET NOT NULL;
ALTER TABLE user_logins ALTER COLUMN login_provider SET DEFAULT '';

CREATE TABLE countries (
    country_id integer GENERATED BY DEFAULT AS IDENTITY,
    country_name character varying(70) NOT NULL,
    CONSTRAINT "PK_countries" PRIMARY KEY (country_id)
);

CREATE TABLE regions (
    region_id integer NOT NULL,
    country_id integer NOT NULL,
    region_name text NOT NULL,
    CONSTRAINT "PK_regions" PRIMARY KEY (region_id),
    CONSTRAINT "FK_regions_countries_region_id" FOREIGN KEY (region_id) REFERENCES countries (country_id) ON DELETE CASCADE
);

CREATE TABLE cities (
    city_id integer GENERATED BY DEFAULT AS IDENTITY,
    region_id integer NOT NULL,
    name_city text NOT NULL,
    time_zone text NOT NULL,
    coordinates geometry (point) NOT NULL,
    CONSTRAINT "PK_cities" PRIMARY KEY (city_id),
    CONSTRAINT "FK_cities_regions_region_id" FOREIGN KEY (region_id) REFERENCES regions (region_id) ON DELETE CASCADE
);

CREATE TABLE "CityServiceModel" (
    "CitiesCityId" integer NOT NULL,
    "ServicesServiceId" integer NOT NULL,
    CONSTRAINT "PK_CityServiceModel" PRIMARY KEY ("CitiesCityId", "ServicesServiceId"),
    CONSTRAINT "FK_CityServiceModel_cities_CitiesCityId" FOREIGN KEY ("CitiesCityId") REFERENCES cities (city_id) ON DELETE CASCADE,
    CONSTRAINT "FK_CityServiceModel_services_ServicesServiceId" FOREIGN KEY ("ServicesServiceId") REFERENCES services (service_id) ON DELETE CASCADE
);

CREATE INDEX "IX_cities_city_id" ON cities (city_id);

CREATE INDEX "IX_cities_region_id" ON cities (region_id);

CREATE INDEX "IX_CityServiceModel_ServicesServiceId" ON "CityServiceModel" ("ServicesServiceId");

CREATE INDEX "IX_countries_country_id" ON countries (country_id);

CREATE INDEX "IX_regions_country_id" ON regions (country_id);

CREATE INDEX "IX_regions_region_id" ON regions (region_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240731171115_AddContryRegionAndCity', '8.0.7');

COMMIT;

START TRANSACTION;

DROP TABLE "CityServiceModel";

CREATE TABLE city_to_service (
    city_id integer NOT NULL,
    "ServicesServiceId" integer NOT NULL,
    service_id integer NOT NULL,
    CONSTRAINT "PK_city_to_service" PRIMARY KEY (city_id, "ServicesServiceId"),
    CONSTRAINT "FK_city_to_service_cities_city_id" FOREIGN KEY (city_id) REFERENCES cities (city_id) ON DELETE CASCADE,
    CONSTRAINT "FK_city_to_service_services_ServicesServiceId" FOREIGN KEY ("ServicesServiceId") REFERENCES services (service_id) ON DELETE CASCADE
);

CREATE INDEX "IX_city_to_service_ServicesServiceId" ON city_to_service ("ServicesServiceId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240731201837_AddCityToService', '8.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE city_to_service DROP CONSTRAINT "FK_city_to_service_services_ServicesServiceId";

ALTER TABLE city_to_service DROP CONSTRAINT "PK_city_to_service";

DROP INDEX "IX_city_to_service_ServicesServiceId";

ALTER TABLE city_to_service DROP COLUMN "ServicesServiceId";

ALTER TABLE city_to_service ADD CONSTRAINT "PK_city_to_service" PRIMARY KEY (city_id, service_id);

CREATE INDEX "IX_city_to_service_service_id" ON city_to_service (service_id);

ALTER TABLE city_to_service ADD CONSTRAINT "FK_city_to_service_services_service_id" FOREIGN KEY (service_id) REFERENCES services (service_id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240731202133_AddKeyCityToService', '8.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE services ALTER COLUMN description_service DROP NOT NULL;

ALTER TABLE categories_services ALTER COLUMN description DROP NOT NULL;

ALTER TABLE services ADD CONSTRAINT ck_service_duration CHECK (duration > 0);

ALTER TABLE services ADD CONSTRAINT ck_service_price CHECK (price > 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240801155350_AddCheckConstraintEnyProperties', '8.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE regions ALTER COLUMN region_name TYPE character varying(70);

ALTER TABLE countries ALTER COLUMN country_name DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240801190809_AddMaxLengthRegionName', '8.0.7');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240801193632_RenamePropertiesForCountryRegionCity', '8.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE regions ALTER COLUMN region_id DROP DEFAULT;
ALTER TABLE regions ALTER COLUMN region_id ADD GENERATED BY DEFAULT AS IDENTITY;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240801205523_UseIdentityRegionIdColumn', '8.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE regions DROP CONSTRAINT "FK_regions_countries_region_id";

ALTER TABLE regions ADD CONSTRAINT "FK_regions_countries_country_id" FOREIGN KEY (country_id) REFERENCES countries (country_id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240801210005_DeleteRelationCountryToRegions', '8.0.7');

COMMIT;

